### ISSUE TITLE
Bricklayer_layout issue

### ISSUE THREAD

**Issue by sgomezp** [getgrav/grav-theme-quark#64]
Hi!

I already posted this issue on [hibbitts-design/grav-theme-quark-open-publishing](https://github.com/hibbitts-design/grav-theme-quark-open-publishing/issues/8#issuecomment-430285990)

Like Quark theme is the parent of **grav-theme-quark-open-publishing** I  open the issue here (The problem is the same using Quark Theme).

In my blog.md file I have the following configuration:

```
content:
    items:
        - '@self.children'
    limit: 4
    order:
        by: date
        dir: desc
    pagination: true
    url_taxonomy_filters: true
bricklayer_layout: true
```

The bricklayer_layout works fine in Chrome but not in Edge. When you open the page in Edge the posts are displayed in a single column.
Please, could you help me to resolve this issue?
This is my website: [sandragomezs.com](https://sandragomezs.com)

Thank you so much!
Best regards,

Sandra
