### ISSUE TITLE
allow the site title to be next to the logo in the navbar

### ISSUE THREAD

**Issue by aoloe** [getgrav/grav-theme-quark#84]
many sites want a text next to the logo in the navigation bar.

i have modified `logo.html.twig` to be:

```twig
  {% set logo_file = (logo|first).name %}
  <img src="{{ url('theme://images/logo/' ~ logo_file)  }}" alt="{{ site.name }}" />
  {{ site.title|e('html') }}
```
but it should probably be an option...

the css is then:

```css

#header .logo a.navbar-brand img {
  display: inline-block;
  vertical-align: middle;
  margin-right: 0.5rem;
}
```
