### ISSUE TITLE
Full width grid not usable

### ISSUE THREAD

**Issue by mauricemeyer** [getgrav/grav-theme-quark#85]
The options in the `blueprints.yaml` specify a default value of `'': None (full width)`:

```
grid-size:
  type: select
  label: Grid size
  help: The maximum width of the theme
  size: small
  options:
    '': None (full width)
    grid-xl: Extra Large
    grid-lg: Large
    grid-md: Medium
```

Due to the usage of the variable, the option has to have the value `''` which makes it selectable only by deleting any other text from the field (which is inconvenient, but I haven’t found a clean way to solve that yet).

However, once you „select“ full width, you’ll end up with `grid-lg`, as this is the default from `quark.yaml` - because the value set by the user is an empty string, so the fallback to the theme default occurs.

Is it intended that the full width mode is not usable (I could imagine that as I found a bug in the display of blog items using it) or do you consider this a bug? 

If it is considered a bug, I would provide a PR that: 

* changes the default to `''` (if you have better ideas, let me know!)
* changes the image `cropZoom` values in `templates/partials/blog-list-item.html.twig` to sensible defaults for the different layout sizes (hard thing about that: If it’s full width, which width in pixels should be used? A screen could theoretically have an infinite number of pixels in the horizontal direction, so I could maybe make it work up to 4K or 8K?)
